### ISSUE TITLE
Search does not put autocomplete name matches high enough in the search results.

### ISSUE THREAD

**Issue by mhilton** [juju/charmstore#614]
A search like https://api.jujucharms.com/charmstore/v5/search?text=juju-g&autocomplete=1 is boosting other results over some prefix matches. The prefix matches should come first.

**Comment by mhilton** [comment]
Fixed by #624.

**Comment by frankban** [comment]
This is not yet fixed, https://api.jujugui.org/charmstore/v5/search?text=juju-g&autocomplete=1 now returns no results.

**Comment by frankban** [comment]
This seems to be fixed now.
